DROP TABLE PEDESTALS_VALUE;
DROP TABLE PEDESTALS;
CREATE TABLE PEDESTALS( IOV_VALUE_ID NUMBER(38) NOT NULL, TILLTIME NUMBER(38), PRIMARY KEY(IOV_VALUE_ID));

CREATE TABLE PEDESTALS_VALUE( POS NUMBER(38) NOT NULL, IOV_VALUE_ID NUMBER(38) NOT NULL, MEAN FLOAT(126) NOT NULL, VARIANCE FLOAT(126) NOT NULL, PRIMARY KEY(IOV_VALUE_ID,POS) , FOREIGN KEY(IOV_VALUE_ID) REFERENCES PEDESTALS(IOV_VALUE_ID));

SELECT INDEX_NAME, TABLE_NAME FROM USER_INDEXES;

INSERT INTO PEDESTALS VALUES( 0, 1997 );
INSERT INTO PEDESTALS VALUES( 1, 1998 );
INSERT INTO PEDESTALS VALUES( 2, 1999 );

INSERT INTO PEDESTALS_VALUE VALUES(0, 0, 1.1, 0.1);
INSERT INTO PEDESTALS_VALUE VALUES(1, 0, 1.2, -0.1);
INSERT INTO PEDESTALS_VALUE VALUES(2, 0, 1.3, 0.1);
INSERT INTO PEDESTALS_VALUE VALUES(3, 0, 1.4, -0.1);

INSERT INTO PEDESTALS_VALUE VALUES(0, 1, 2.1, 0.1);
INSERT INTO PEDESTALS_VALUE VALUES(1, 1, 2.2, -0.1);
INSERT INTO PEDESTALS_VALUE VALUES(2, 1, 2.3, 0.1);
INSERT INTO PEDESTALS_VALUE VALUES(3, 1, 2.4, -0.1);

INSERT INTO PEDESTALS_VALUE VALUES(0, 2, 3.1, 0.1);
INSERT INTO PEDESTALS_VALUE VALUES(1, 2, 3.2, -0.1);
INSERT INTO PEDESTALS_VALUE VALUES(2, 2, 3.3, 0.1);
INSERT INTO PEDESTALS_VALUE VALUES(3, 2, 3.4, -0.1);
